### PR TITLE
Rename Exchange to Hub in ReadMe

### PR DESCRIPTION
**Pull request by nehavarghese**
Signed-off-by: Neha Varghese <neha.v@ibm.com>

## PR Checklist
Please make sure that your PR fulfills the following requirements:  
- [x] The commit message follows the [Angular Commit Message Guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines).
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type  

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] New tests
- [ ] Build/CI related changes
- [x] Documentation content changes
- [ ] Other (please describe)

## Does this PR introduce a breaking change?    
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by jennalc — APPROVED** [review]
Looks good

**Review by jennalc — APPROVED** [review]
Looks good

**Comment by nehavarghese** [comment]
Hi @jennalc ,

Please review an additional change added to this PR, regarding the Travis build configuration.
Change is suggested by Travis support team as below:
**_Can you please change group: focal to group: stable within .travis.yml and see if that resolves the issue? group: focal is not a recognized so either stable needs to be used or the group: stable can be safely dropped as a whole since it is the default group for the builds._**

the same has been implemented and build is success now after changing group tag to stable.

**Pull request merged**
